baseurl = "https://almhof.netlify.app/"
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
enableGitInfo = false
enableRobotsTXT = true
languageCode = "en-US"
paginate = 7

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

copyright = "Copyright (c) 2020-2021 Almhof"

# add redirects/headers
[outputs]
home = ["HTML"]
section = ["HTML", "SITEMAP"]

# add output format for section sitemap.xml
[outputFormats.SITEMAP]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = true
noUgly = true
rel  = "sitemap"

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10s"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  contributor = "contributors"

[permalinks]
  news = "/news/:title/"

[minify.tdewolff.html]
  keepWhitespace = false

[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"