[en]
  languageName = "English"
  languageCode = "en"
  weight = 10
  [en.params]
    languageISO = "EN"

[de]
  languageName = "German"
  languageCode = "de"
  weight = 15
  [de.params]
    languageISO = "DE"

[nl]
  languageName = "Nederlands"
  languageCode = "nl"
  weight = 20
  [nl.params]
    languageISO = "NL"
    titleAddition = "B&B in het hart van Karinthie"
    description = "Doks is een Hugo-thema waarmee je moderne documentatie-websites kunt bouwen die veilig, snel en klaar voor SEO zijn — standaard."
    titleHome = "Doks thema"