# Meta Data for SEO

## Homepage
title = "Pension almhof"
titleSeparator = "-"
titleAddition = "B&B in the heart of Carinthia" 
description = "Doks is a Hugo theme for building secure, fast, and SEO-ready documentation websites, which you can easily update and customize."

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "almhof.netlify.app"
titleHome = "Pension Almhof"

## Twitter Cards
twitterSite = "@getdoks"
twitterCreator = "@henkverlinde"

## JSON-LD
schemaType = "Organization"
schemaName = "Pension Almhof"
schemaAuthor = "Danny Dorstijn"
schemaAuthorTwitter = ""
schemaAuthorLinkedIn = "https://www.linkedin.com/in/ddorstijn/"
schemaAuthorGitHub = "https://github.com/ddorstijn"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaLinkedIn = ""
schemaSection = ""

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

[options]
  lazySizes = true
  instantPage = true