backend:
  name: git-gateway
  branch: master

media_folder: assets/images
public_folder: /images

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  structure: multiple_files

  # Required - a list of locales to show in the editor UI
  locales: [en, de, nl]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
  - name: homepage
    label: Homepage
    folder: content/homepage
    create: false
    i18n: true
    fields:
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Section
        name: section
        widget: hidden
      - label: Images
        name: images
        widget: image
        allow_multiple: false
        i18n: duplicate
      - label: Draft
        name: draft
        widget: hidden
        default: false
        i18n: duplicate
      - label: Body
        name: body
        widget: markdown
        i18n: true
  - name: news
    label: News
    folder: content/news
    create: true
    i18n: true
    fields:
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Description
        name: description
        widget: string
        i18n: true
      - label: Lead
        name: lead
        widget: string
        i18n: true
      - label: Date
        name: date
        widget: datetime
        i18n: duplicate
      - label: Last modified
        name: lastMod
        widget: hidden
        i18n: duplicate
      - label: Weight
        name: weight
        widget: number
        i18n: duplicate
      - label: Images
        name: images
        widget: image
        i18n: duplicate
      - label: Draft
        name: draft
        widget: boolean
        default: true
        i18n: duplicate
      - label: Body
        name: body
        widget: markdown
        i18n: true
  - name: rooms
    label: Rooms
    create: true
  - name: facilities
    label: Facilities
    create: true
  - name: activities
    label: Activities
    create: true
  - name: reviews
    label: Reviews
    create: true